nubis/puppet/files/eni-associate

Filtering for available ENI's need to be more specific, fixes #7

Fixing filters to be more specific

---

README.md
nubis/puppet/00_nat.pp
nubis/puppet/files/interface-fixup
nubis/puppet/files/nat/confd/conf.d/iptables.toml
nubis/puppet/files/nat/confd/templates/iptables.tmpl

Managing iptable rules via confd for nat instance, fixes issue #20

Manage iptable rules via confd

---

nubis/puppet/04_blocklist.pp
nubis/puppet/files/vpc-blocklist

POC: Implement a VPC blocklisting process.

---

nubis/puppet/files/interface-fixup

Move Consul advertisement to eth1

---

nubis/puppet/00_nat.pp
nubis/puppet/01_eip.pp
nubis/puppet/files/interface-fixup

Fixing ordering for the new consul-wait in base.

---

nubis/puppet/files/vpc-blocklist

Change default blacklist polling location and disable GPG verification by default

---

nubis/puppet/files/vpc-blocklist

Use detected region

---

nubis/puppet/00_params.pp

Latest git in Amazon Linux is 2.7.3-1.46.amzn1

---

nubis/puppet/files/nat/eni-associate

Remove routes properly, previously it was not removing it because the routes had not shown up. So now we wait for it until it shows up

Remove redundant route

---

nubis/puppet/00_nat.pp
nubis/puppet/03_fluentd.pp
nubis/puppet/files/nat/logging/99-iptables.conf
nubis/puppet/files/nat/logging/logrotate_iptables.conf

Filter out iptable log to its own file and send it out via fluent

---

nubis/puppet/files/nat/eni-associate

Missed clearing up some debugging information from eni attach script

Remove debugging code

---

nubis/puppet/files/nat/eip-attach

check metadata for assigned EIP first

---

nubis/puppet/files/nat/eni-associate

Detach our ENI if already atached, before grabbing it.

---

nubis/puppet/files/interface-fixup
nubis/puppet/files/nat/confd/templates/iptables.tmpl

This way, we get away with confd fiddling
Fixes #82

Use facter to find our VPC cidr range.

---

nubis/puppet/files/nat/eni-associate

Fix bug that caused ENI detaching logic not to wait for it to actually detach

---

nubis/puppet/files/nat/confd/templates/iptables.tmpl

Allow Squid traffic inbound on any interfaces

---

nubis/puppet/files/vpc-blocklist

Correctly use the action passed into create_acl()

---

nubis/puppet/files/vpc-blocklist

Handle gracefully (skip them) blocklist that have more than MAX_RULES(18) entries

---

nubis/puppet/files/vpc-blocklist

Small cleanup and off-by-one error

---

nubis/Puppetfile

Pin nubis-puppet-nat to version v1.2.0

---

nubis/Puppetfile

Pinning puppet nsm to v1.2.0

---

nubis/builder/project.json

Bump up to v1.3.0-dev cycle

---

README.md

Added additional documentation on how to test FORWARD rule

---

nubis/puppet/00_params.pp
nubis/puppet/01_proxy.pp

Cleanup old nubis-skel cruft

---

nubis/puppet/03_fluentd.pp

Build a regexp to parse Squid access-logs

---

nubis/puppet/03_fluentd.pp

Include milliseconds from squid's access logs

---

nubis/puppet/03_fluentd.pp

Parse (partial) of iptables's reject logs

---

nubis/puppet/files/vpc-blocklist

use consul-do || exit 0 to keep cron job succeeding

---

nubis/puppet/files/nat/eni-associate

Typo fix to actually detect interface readiness and not just fall through

---

nubis/puppet/00_params.pp
nubis/puppet/03_fluentd.pp
nubis/puppet/files/nat/eni-associate
nubis/puppet/snmp_exporter.pp

ec2 wait instance-running on ourselves is completely redundant

---

nubis/puppet/00_nat.pp

As requested from issue nubisproject/nubis-puppet-nsm#12

Change email address for nsm

---

nubis/puppet/files/interface-fixup
nubis/puppet/files/squid-exporter/svc-squid-exporter.json

Use proper interface for squid exporter service

---

nubis/puppet/02_squid.pp

Allow outbound SSL connections on tcp/8443
